In [2]:
import pandas as pd
import numpy as np
import matplotlib as plt

**Pandas**: Assignment 1: Reads csv file as pandas dataframe, and prints first 5 and last 10 rows of the data

In [ ]:
dataframe = pd.read_csv('/content/sample_data/california_housing_train.csv')
f5rows = dataframe.head(5)
l10rows = dataframe.tail(10)
print(f5rows)
print(l10rows)

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0  
       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16990    -124.22     41.73                28.0       3003.0           699.0   
16991    -124

Assignment 2: Providing a numerical summary of the dataset

In [ ]:
dataframe.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

Find the number of unique items, and also all the different unique items present under total_bedrooms

In [ ]:
total_bedrooms_items = dataframe['total_bedrooms'].value_counts()
# print(total_bedrooms_items)
distinct_items = 0
print("The distinct elements are: ")
for i in total_bedrooms_items.keys():
  print(i, end=" ")
  distinct_items += 1
print('\n And the total number of unique items is: ', distinct_items)

total_bedrooms
280.0     48
309.0     44
331.0     43
394.0     43
345.0     43
          ..
2405.0     1
1797.0     1
1024.0     1
1494.0     1
936.0      1
Name: count, Length: 1848, dtype: int64
The distinct elements are: 
280.0 309.0 331.0 394.0 345.0 343.0 290.0 340.0 272.0 322.0 295.0 291.0 353.0 294.0 328.0 398.0 313.0 335.0 399.0 346.0 254.0 282.0 393.0 317.0 361.0 388.0 289.0 390.0 308.0 348.0 410.0 284.0 307.0 277.0 426.0 427.0 325.0 447.0 315.0 271.0 372.0 369.0 287.0 312.0 411.0 406.0 300.0 310.0 408.0 344.0 365.0 342.0 269.0 228.0 306.0 338.0 339.0 379.0 428.0 460.0 472.0 373.0 366.0 363.0 359.0 419.0 391.0 444.0 332.0 482.0 358.0 370.0 386.0 356.0 360.0 412.0 409.0 292.0 418.0 357.0 354.0 477.0 435.0 297.0 468.0 478.0 352.0 246.0 416.0 347.0 396.0 401.0 316.0 389.0 314.0 430.0 387.0 431.0 464.0 236.0 263.0 303.0 371.0 502.0 261.0 518.0 266.0 404.0 278.0 324.0 279.0 235.0 375.0 301.0 311.0 275.0 454.0 276.0 238.0 417.0 273.0 422.0 559.0 250.0 323.0 415.0 240.0 501.0 438.0 

Assignment 3: Add a new column called total_bedrooms_per_total_rooms and calculate it's mean and standard deviation

In [ ]:
tbptr = []
tbptrnum = 0
for i in range(len(dataframe.index)): # as num of records is 17000
  tbptr.append(dataframe.values[i][4]/dataframe.values[i][3])
  tbptrnum += dataframe.values[i][4]/dataframe.values[i][3]
dataframe['total_bedrooms_per_total_rooms'] = tbptr
# print(dataframe)
mean = tbptrnum/17000
stdeviation = dataframe['total_bedrooms_per_total_rooms'].std()
print("Mean is ", mean, " and std is ", stdeviation)


Mean is  0.2127599882103483  and std is  0.057823008903161756


Assignment 4: Filter dataset to find rows with median income greater than 5, also to create a new dataset with total rooms > 10000 and median house value under 150000, and then create this dataframe into a csv file

In [ ]:
filtered_rows = [] # will contain all the row indeces of rows with median_income greater than 5
for i in range(len(dataframe.index)):
  if (dataframe.values[i][7] > 5):
    filtered_rows.append(i)
# for i in filtered_rows: # prints all the rows with median_income > 5
#   print(dataframe.values[i])
rows_tb_removed = []
for i in range(len(dataframe.index)):
  if dataframe.values[i][3] < 10000 or dataframe.values[i][8] > 150000:
    rows_tb_removed.append(i)
subset = dataframe.drop(rows_tb_removed)
subset.to_csv('subset.csv', index = False, encoding='utf-8')

**Numpy**: Assignment 1: makes an array containing nums 1 to 20 in numpy, prints even numbers only and makes a random 2d array with 5 rows and 4 columns, which it then further crops to 3 rows and 2 columns

In [ ]:
nums = []
for i in range(1, 21):
  nums.append(i)
arr = np.array(nums)
even = arr[1::2]
two_d_array = np.random.randint(10,90,(5,4))
# print(two_d_array)
cropped_array = two_d_array[:3, :2]
# print(cropped_array)

[[58 57 33 41]
 [10 73 42 57]
 [63 58 41 12]
 [84 43 73 52]
 [68 85 79 35]]
[[58 57]
 [10 73]
 [63 58]]


Assignment 2: reshapes a 1d array to 2d and then reshapes it again to 1d. performs matrix multiplication between 2 2d arrays

In [ ]:
reshaped_array = arr.reshape(5, 4)
# print(reshaped_array)
unreshaped_array = reshaped_array.flatten()
print(unreshaped_array)
two_d_array2 = np.random.randint(1, 5,(4,5))
matmul = np.matmul(two_d_array2, reshaped_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Assignment 3: makes an array of length 50 with random numbers, and filters the array with a binary mask. also uses fancy indexing to extract elements at specific indexes from the array

In [ ]:
random_arr = np.random.randint(0, 100, 50)
bmask = random_arr > 50
narr = random_arr[bmask]
indices = np.random.choice(range(50), 10, replace=False)
farr = random_arr[indices]

[43 36 29 66 46 45 66 72 33 98] [37 31 14 48 30 21  1 43 20 13]


Assignment 4: finds mean max and sum along each array for the 2d matrix created earlier, filters the array by making a mask to filter each column by removing elements less than the mean

In [ ]:
sum_column = []
max_column = []
columns = []
for i in range(4):
  max_column.append(two_d_array[0][i])
  sum_column.append(0)
  columns.append(two_d_array[:, i:i+1])
  for j in two_d_array[:, i:i+1]:
    sum_column[i] += j
    if max_column[i] < j:
      max_column[i] = j
# print(two_d_array)
# print(sum_column, max_column)
mean_column = []
for i in range(4):
  mean_column.append(sum_column[i]/5)
# print(mean_column)
# print(columns)
for i in range(4):
  bmask = columns[i] > mean_column[i]
  columns[i] = columns[i][bmask]
# print(columns)

[array([[58],
       [10],
       [63],
       [84],
       [68]]), array([[57],
       [73],
       [58],
       [43],
       [85]]), array([[33],
       [42],
       [41],
       [73],
       [79]]), array([[41],
       [57],
       [12],
       [52],
       [35]])]
[array([58, 63, 84, 68]), array([73, 85]), array([73, 79]), array([41, 57, 52])]


**Problem Solving**: Assignment 1: prints first 50 fibonacci numbers, and then from 1 to 50 types fizz if multiple of 3, buzz if multiple of 5, fizzbuzz if both.

In [ ]:
a = 1
b = 1
print(a, end=" ")
for i in range(49):
  print(b, end=" ")
  b = a + b
  a = b - a
print("\n")
for i in range(1, 51):
  if i%3 == 0 and i%5 == 0:
    print("FizzBuzz", end=" ")
    continue
  if i%3 == 0:
    print("Fizz", end=" ")
  if i%5 == 0:
    print("Buzz", end=" ")

1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 6765 10946 17711 28657 46368 75025 121393 196418 317811 514229 832040 1346269 2178309 3524578 5702887 9227465 14930352 24157817 39088169 63245986 102334155 165580141 267914296 433494437 701408733 1134903170 1836311903 2971215073 4807526976 7778742049 12586269025 

Fizz Buzz Fizz Fizz Buzz Fizz FizzBuzz Fizz Buzz Fizz Fizz Buzz Fizz FizzBuzz Fizz Buzz Fizz Fizz Buzz Fizz FizzBuzz Fizz Buzz 

Assignment 2: returns median and mean of a variable length of numbers given by the user

In [ ]:
n = int(input("length of the array? "))
arr = []
sum = 0
for i in range(n):
  inp = int(input("Enter Value: "))
  arr.append(inp)
  sum += inp
arr.sort()
mean = inp/n
if n%2 == 0:
  median = (arr[int(n/2)] + arr[int(n/2) - 1])/2
else:
  median = arr[int((n-1)/2)]
# print(median, mean)

length of the array? 5
Enter Value: 4
Enter Value: 54
Enter Value: 32
Enter Value: 7
Enter Value: 1
7


Assignment 3: handles the division by zero by returning a message instead

In [ ]:
n = int(input("Enter divisor: "))
try:
  ans = 15/n
except ZeroDivisionError:
  print("You can not divide by zero")

Enter divisor: 0
You can not divide by zero


Extra Assignments: Assignment 1: creates a 3d array with random numbers, then swaps 2 of it's axes and then finds the sum along each of it's axes. Then shows the effect of broadcasting by adding one d array to 2d array through simple addition operation.

In [8]:
three_d_arr = np.random.randint(1, 100, (3, 3, 3))
# print(three_d_arr)
swapped_mat = three_d_arr.transpose()
# print(swapped_mat) #swapped out 2 of the axes through transposing the matrix
sum_along_x = 0
sum_along_y = 0
sum_along_z = 0
for i in range(3):
  for j in range(3):
    sum_along_y += three_d_arr[i][j][0]
    if (j == 2):
      for k in range(3):
        sum_along_x += three_d_arr[i][j][k]
  if (i == 2):
    for j in range(3):
      for k in range(3):
        sum_along_z += three_d_arr[i][j][k]
# print(sum_along_x, sum_along_y, sum_along_z)

one_d_arr = np.random.randint(1, 10, 3)
an_2d_arr = np.random.randint(1, 10, (3, 3))
added_arr = an_2d_arr + one_d_arr #displays the effect of broadcasting, adds a vector to the matrix
# print(one_d_arr)
# print(an_2d_arr)
# print(added_arr)

[[[83 72 21]
  [68 14 97]
  [61 34 10]]

 [[65 90 52]
  [71 40 15]
  [96  5 17]]

 [[67  8 22]
  [71 67  5]
  [ 9 88 27]]]
347 591 364
